default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: <%= ENV['app_name'] %>_development
  # No password for local DB, using trust connection

test:
  <<: *default
  database: <%= ENV['app_name'] %>_test
  # No password for local DB, using trust connection

production:
  <<: *default
  host: <%= ENV['postgres_host'] %>
  port: <%= ENV['postgres_port'] %>
  database: <%= ENV['postgres_database'] %>
  username: <%= ENV['postgres_username'] %>
  password: <%= ENV['postgres_password'] %>

staging:
  <<: *default
  host: <%= ENV['postgres_host'] %>
  port: <%= ENV['postgres_port'] %>
  database: <%= ENV['postgres_database'] %>
  username: <%= ENV['postgres_username'] %>
  password: <%= ENV['postgres_password'] %>
